easy_admin:
    site_name: 'Administration'
    design:
        brand_color: 'rgba(26, 188, 156, 0.85)'
        menu:
#            - { label: 'Tableau de bord', icon: 'dashboard', route: 'admin_homepage', default: true }
            - { label: 'Utilisateurs', entity: 'User', icon: 'users' }
    entities:
        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
        - App\Entity\User
